/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_paolo_jvmti_jvmtiEnv */

#ifndef _Included_jvmtiWrapCapabilities
#define _Included_jvmtiWrapCapabilities

#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     me_paolo_jvmti_jvmtiEnv
	 * Method:    AddCapabilities
	 * Signature: (Lme/paolo/jvmti/jvmtiCapabilities;)Lme/paolo/jvmti/jvmtiError;
	 */
	JNIEXPORT jobject JNICALL Java_me_paolo_jvmti_jvmtiEnv_AddCapabilities
	(JNIEnv*, jclass, jobject);

	/*
	 * Class:     me_paolo_jvmti_jvmtiEnv
	 * Method:    RelinquishCapabilities
	 * Signature: (Lme/paolo/jvmti/jvmtiCapabilities;)Lme/paolo/jvmti/jvmtiError;
	 */
	JNIEXPORT jobject JNICALL Java_me_paolo_jvmti_jvmtiEnv_RelinquishCapabilities
	(JNIEnv*, jclass, jobject);

	/*
	 * Class:     me_paolo_jvmti_jvmtiEnv
	 * Method:    GetCapabilities
	 * Signature: ()Lme/paolo/jvmti/jvmtiCapabilities;
	 */
	JNIEXPORT jobject JNICALL Java_me_paolo_jvmti_jvmtiEnv_GetCapabilities
	(JNIEnv*, jclass);
#ifdef __cplusplus
}
#endif
#endif
