/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <jvmti.h>
/* Header for class me_paolo_jvmti_jvmtiEnv */

#ifndef _Included_jvmtiWrap
#define _Included_jvmtiWrap
extern jvmtiEnv* jvmti;

#ifdef __cplusplus
extern "C" {
#endif
	JNIEXPORT jint JNICALL JNI_OnLoad
	(JavaVM*, void*);
#ifdef __cplusplus
}
#endif
#endif
