/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_paolo_jvmti_jvmtiEnv */

#ifndef _Included_jvmtiWrapCallbacks
#define _Included_jvmtiWrapCallbacks
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     me_paolo_jvmti_jvmtiEnv
	 * Method:    SetEventCallbacks
	 * Signature: (Lme/paolo/jvmti/event/jvmtiEventCallbacks;)Lme/paolo/jvmti/jvmtiError;
	 */
	JNIEXPORT jobject JNICALL Java_me_paolo_jvmti_jvmtiEnv_SetEventCallbacks
	(JNIEnv*, jclass, jobject);

	/*
	 * Class:     me_paolo_jvmti_jvmtiEnv
	 * Method:    SetEventNotificationMode
	 * Signature: (Lme/paolo/jvmti/event/jvmtiEventMode;Lme/paolo/jvmti/event/jvmtiEvent;Ljava/lang/Thread;)Lme/paolo/jvmti/jvmtiError;
	 */
	JNIEXPORT jobject JNICALL Java_me_paolo_jvmti_jvmtiEnv_SetEventNotificationMode
	(JNIEnv*, jclass, jobject, jobject, jobject);
#ifdef __cplusplus
}
#endif
#endif
