/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_paolo_jvmti_jvmtiEnv */

#ifndef _Included_jvmtiWrapInstrumentation
#define _Included_jvmtiWrapInstrumentation
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     me_paolo_jvmti_jvmtiEnv
	 * Method:    GetLoadedClasses
	 * Signature: ()[Ljava/lang/Class;
	 */
	JNIEXPORT jobjectArray JNICALL Java_me_paolo_jvmti_jvmtiEnv_GetLoadedClasses
	(JNIEnv*, jclass);

	/*
	 * Class:     me_paolo_jvmti_jvmtiEnv
	 * Method:    GetClassLoaderClasses
	 * Signature: (Ljava/lang/ClassLoader;)[Ljava/lang/Class;
	 */
	JNIEXPORT jobjectArray JNICALL Java_me_paolo_jvmti_jvmtiEnv_GetClassLoaderClasses
	(JNIEnv*, jclass, jobject);

	/*
	 * Class:     me_paolo_jvmti_jvmtiEnv
	 * Method:    RetransformClasses
	 * Signature: ([Ljava/lang/Class;)Lme/paolo/jvmti/jvmtiError;
	 */
	JNIEXPORT jobject JNICALL Java_me_paolo_jvmti_jvmtiEnv_RetransformClasses
	(JNIEnv*, jclass, jobjectArray);

	/*
	 * Class:     me_paolo_jvmti_jvmtiEnv
	 * Method:    RedefineClasses
	 * Signature: ([Lme/paolo/jvmti/jvmtiClassDefinition;)Lme/paolo/jvmti/jvmtiError;
	 */
	JNIEXPORT jobject JNICALL Java_me_paolo_jvmti_jvmtiEnv_RedefineClasses
	(JNIEnv*, jclass, jobjectArray);
#ifdef __cplusplus
}
#endif
#endif
